# Generated by Django 2.2.5 on 2019-09-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='time_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
