# Generated by Django 2.2.5 on 2019-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_education_time_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='time_to',
            new_name='end',
        ),
        migrations.RemoveField(
            model_name='education',
            name='time',
        ),
        migrations.AddField(
            model_name='education',
            name='join',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='join',
            field=models.DateField(blank=True, null=True),
        ),
    ]
