# Generated by Django 2.2.5 on 2019-09-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_auto_20190913_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='ending_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='joining_date',
        ),
    ]
