# Generated by Django 2.2.5 on 2019-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0006_auto_20190914_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address',
            field=models.CharField(help_text='Enter Your Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_number',
            field=models.CharField(help_text='Enter Your Mobile Number', max_length=100, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='first_name',
            field=models.CharField(help_text='Enter Your First Name', max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='image',
            field=models.ImageField(help_text='Please Upload 500x500 px Image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='last_name',
            field=models.CharField(help_text='Enter Your Last Name', max_length=100, verbose_name='Last Name'),
        ),
    ]
